name: allow-only-develop-to-master

on:
  pull_request:
    branches:
      - master

jobs:
  validate-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Validate source branch
        run: |
          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "❌ Only PRs from develop to master are allowed."
            exit 1
          fi
          echo "✅ Valid PR from develop"
